---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/Kuniwak/vint
    # TODO change to tag/branch when released
    rev: 9a239b20be279324ced3b34ed71f84a63edfd4fb
    hooks:
      - id: vint

  - repo: https://github.com/eschulte/lisp-format
    # TODO change to tag/branch when released
    rev: 13dd9e603e840bd5d1901860867aeec68f13801a
    hooks:
      - id: lisp-format
